name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, mysql

    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 51.89.148.3 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        rsync -avz --no-times --no-perms --delete --exclude='storage/' --exclude='.git/' ./ root@51.89.148.3:/var/www/

    - name: Set Permissions and Ensure Directories Exist
      run: |
        ssh root@51.89.148.3 "sudo mkdir -p /var/www/storage /var/www/bootstrap/cache /var/www/resources/views && sudo chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache /var/www/resources/views && sudo chmod -R 775 /var/www/storage /var/www/bootstrap/cache /var/www/resources/views"

    - name: Run Migrations and Key Generation
      run: |
        ssh root@51.89.148.3 "cd /var/www && php artisan key:generate && php artisan migrate --force && php artisan config:cache && php artisan route:cache"
