name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, mysql
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Set up SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.89.148.3 >> ~/.ssh/known_hosts

      - name: Sync Files to VPS
        run: |
          rsync -avz --delete \
            --exclude='storage/' \
            --exclude='.git/' \
            ./ root@51.89.148.3:/var/www/vive_admin_panel

      - name: Ensure Laravel Directories and Permissions
        run: |
          ssh root@51.89.148.3 << 'EOF'
            cd /var/www/vive_admin_panel
            mkdir -p storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache
          EOF

      - name: Upload .env File to VPS
        run: |
          # Copy the .env file from the repository to the VPS
          scp .env root@51.89.148.3:/var/www/vive_admin_panel/.env

      - name: Run Laravel Commands
        run: |
          ssh root@51.89.148.3 << 'EOF'
            cd /var/www/vive_admin_panel
            php artisan config:clear
            php artisan key:generate
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
          EOF
