name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, pdo, mysql
        tools: composer

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 51.89.148.3 >> ~/.ssh/known_hosts

    - name: Clear Laravel Cache on Server
      run: |
        ssh root@51.89.148.3 << 'EOF'
          cd /var/www/vive_admin_panel
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
        EOF

    - name: Deploy to VPS
      run: |
        rsync -avz --no-times --no-perms --delete \
          --exclude=".env" \
          --exclude="storage/" \
          --exclude=".git/" \
          ./ root@51.89.148.3:/var/www/vive_admin_panel

    - name: Set Permissions and Ensure Directories Exist
      run: |
        ssh root@51.89.148.3 << 'EOF'
          cd /var/www/vive_admin_panel
          mkdir -p storage bootstrap/cache
          chown -R www-data:www-data storage bootstrap/cache
          chmod -R 775 storage bootstrap/cache
        EOF

    - name: Run Laravel Commands
      run: |
        ssh root@51.89.148.3 << 'EOF'
          cd /var/www/vive_admin_panel
          php artisan key:generate
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
        EOF
